Copy Worker SSH-Key for root user
RevolutionPi/LAVA-tools pull request #5
Opened 2023-05-11 14:15 UTC by RamiGspo

2023-05-11 15:37 UTC, nbuchwitz requested changes

2023-05-11 15:37 UTC, nbuchwitz commented on worker/revpi_factory_reset.sh
> +ssh pi@revpi32346 "sudo cp -r /home/pi/.ssh /root"
```suggestion
sshpass -p "$DEFAULT_PASS" ssh -o StrictHostKeyChecking=no "$DEFAULT_USER"@"$SSH_HOST_RPI" "sudo cp -r /home/pi/.ssh /root"
```

2023-05-11 15:37 UTC, nbuchwitz commented on worker/revpi_factory_reset.sh
> +ssh pi@revpi32346 "sudo chown -R root: /root/.ssh"&& rm /tmp/lava-key.pub"
```suggestion
sshpass -p "$DEFAULT_PASS" ssh -o StrictHostKeyChecking=no "$DEFAULT_USER"@"$SSH_HOST_RPI" "sudo chown -R root: /root/.ssh"
```

What is the `rm /tmp/lava-key.pub` for? If your intention was to remove the tmp file we created in #4, then please add another commit for this. Also the removal must be run on the worker (eg. after the `ssh-copy-id` line).

2023-05-13 06:29 UTC, RamiGspo commented on worker/revpi_factory_reset.sh
> +ssh pi@revpi32346 "sudo chown -R root: /root/.ssh"&& rm /tmp/lava-key.pub"
We do not need another commit...

2023-05-13 06:40 UTC, RamiGspo commented
After making these modifications to the LAVA-worker I have performed several tests and will do some more in the next few days.
Here is some evidence that these changes are working:

Jobs - 2023-05-11-revpi-bullseye-BETA-arm64-lite.img:
[Image installation - 2023-05-11-revpi-bullseye-BETA-arm64-lite.img](https://lava.revpi.kunbus.com/scheduler/job/1394)
[Health check after Image installation - 2023-05-11-revpi-bullseye-BETA-arm64-lite.img](https://lava.revpi.kunbus.com/scheduler/job/1395)
[TestSuite 001 - 2023-05-11-revpi-bullseye-BETA-arm64-lite.img](https://lava.revpi.kunbus.com/scheduler/job/1396)


@nbuchwitz 
I hadn't put it aside or forgotten about it, but in the last 2 days I really haven't had time to do it. I'm sorry for this. Maybe you can still get a good feeling from the tests on your vacation.

2023-05-14 13:24 UTC, nbuchwitz approved these changes

2023-05-15 12:55 UTC, merged